### ISSUE TITLE
BREXX does not seem to prompt for input

### ISSUE THREAD

**Issue by RonH2O** [mgrossmann/brexx370#14] opened 2019-02-04 23:10 UTC
The following exec pushes a string onto the stack. Pulls the string from the stack and displays a message containing the string. This works fine.
**Source:**
```
 000001 push 'Ron Bywater'
 000002 parse pull myname
 000003 say 'Well, hello there:' myname
 000004 exit 0
```
**Input:**
```
ENTER TSO COMMAND OR CLIST BELOW:
 ===> rexx test1

```
**Output:**
```
ENTER TSO COMMAND OR CLIST BELOW:

 ===> rexx test1

 Well, hello there: Ron Bywater
 ***
```
However if I remove the initial PUSH, my expectation is that BREXX should block waiting for input but this does not seem to happen.

**Source** 
```
 000001 /*push 'Ron Bywater'*/
 000002 parse pull myname
 000003 say 'Well, hello there:' myname
 000004 exit 0
```
**Input**
```
ENTER TSO COMMAND OR CLIST BELOW:

 ===> rexx test1
```

**Output**
```
ENTER TSO COMMAND OR CLIST BELOW:

 ===> rexx test1

 Well, hello there:
 ***
```

Is this a defect? Thanks for offering to look into it.

Kind Regards
Ron

**Comment by RonH2O** [comment] 2019-02-05 22:37
Hi Mike - that makes sense. I don't know if it helps but the attached screen shot shows that STDIN is not assigned to the terminal, which indicates you are correct. Unfortunately I don't know how to go about creating that assignment (I did try issuing `'ALLOC FI(STDIN) DA(*)'` in the exec but BREXX abend with a S0C4) - cheers Ron

[Listals.pdf](https://github.com/mgrossmann/brexx370/files/2834145/Listals.pdf)

**Comment by mgrossmann** [comment] 2019-02-06 11:18
That's fascinating. I did it exactly like that. First a FREE FI(STDIN) for safety and then an ALLOC FI(STDIN) DA(*). That didn't solve the real problem, but it didn't cause 0C4 either.

**Comment by RonH2O** [comment] 2019-02-11 01:47
Hi Mike - I changed the allocation of STDIN in SYS2.CMDPROC(REXXINIT) to
```
000017 /*ALLOC FILE(STDIN)    DUMMY */                                   0001716
000018 ALLOC FILE(STDIN)    DA(*)                                               0001816
```
ran REXXINIT in option 6 and that seemed to do the trick in that
 ```
000001 say 'Enter your name:'
 000002 parse pull myname
 000003 say 'Hello there' myname
 000004 exit 0
```

now prompts for input as it should !! 
 ```
------------------------------------------------------------  RFE TSO  -------------------------------------------
ENTER TSO COMMAND OR CLIST BELOW:

 ===> rexx test1

 Enter your name:
Ron Bywater
 Hello there RON BYWATER
 *** 
```
However, there seems to be another issue in that, as I understand it,  PARSE PULL should preserve the case and so it should read 'Ron Bywater' not 'RON BYWATER'. Where would one look to start investigating this?

Kind Regards
Ron

**Comment by mgrossmann** [comment] 2019-02-11 07:45
Hi Ron,

Thanks for testing. 
I have to take a closer look at the STDIN allocation, because I had actually already tested it. Without success. But I can confirm your test results. Maybe it was a bit late that evening. :) 
The main thing is that it works now. We will take over the change of course.

According to the documentation PULL always converts to capital letters. 

> PULL [template] ;
> 
> pops the next string from rexx internal stack. If stack is empty then it prompts for input. Translates it to uppercase and then parses it according to template. Short for PARSE UPPER PULL.

Best Regards
Mike

**Comment by RonH2O** [comment] 2019-02-11 08:16
Hi Mike,

I agree that PULL always folds into uppercase before the parse but, according to the TSO/E REXX Reference manual (SA32-0972-30), PARSE PULL does not. Since I retired I no longer have access to a Z/OS system but ooRexx on my laptop behaves as I expect (i.e. PARSE PULL preserves the capitalisation). Do you think BREXX should behave the same way?

Kind Regards
Ron


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by mgrossmann** [comment] 2019-02-11 08:28
I can check this against z/OS. But if this is described in the IBM documentation, it will be true. We actually want to stay as close as possible to the z/OS version of REXX. So I leave the issue open and we will try to implement the desired behavior.

**Comment by mgrossmann** [comment] 2019-02-11 08:29
Maybe you could open a new case about PARSE PULL?

**Comment by mgrossmann** [comment] 2019-02-11 09:39
If only PULL is coded instead of PARSE PULL, this corresponds to a PARSE UPPER PULL.

**Comment by mgrossmann** [comment] 2019-02-11 17:13
I'm closing this case at this point. 
The problem with the STDIN allocation will be noted in the documentation. 
For the PARSE PULL problem I opened a new case. [#17 (https://github.com/mgrossmann/brexx370/issues/17)

**Closed** 2019-02-11 17:15 UTC
Labels: documentation, environment
